name: simple-mail-sender

services:
  simple-mail-sender:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple-mail-sender
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
